---
experiment:
  name: graphembed/utzappos/base
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: graphfull
  dropout: true
  norm: true
  nlayers: 1
  fc_emb: 768,1024,1200
  gr_emb: d4096,d
  emb_dim: 300
  emb_init: null
  graph_init: utils/utzappos-graph.t7
  eval_type: otherdist
  image_extractor: resnet18
  train_only: true
  static_inp: false
  composition: mlp_add
gcnii:
  hidden_dim: 1024
  gcn_type: gcn
  gcn_nlayers: 10
training:
  batch_size: 128
  eval_val_every: 2
  load: 
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  max_epochs: 100
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: true
  freeze_features: false
extra:
  lambda_attr: 0
  lambda_obj: 0
  lambda_sub: 0
  graph: false
  hardk: null
  cutmix: false
  cutmix_prob: 1.0
  beta: 1.0